import type { Profile } from '@/types/database'

// Mock profiles for testing
export const mockProfiles: Profile[] = [
  {
    id: 'mock-1',
    email: 'yuki.tanaka@example.com',
    display_name: '田中 優希',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    bio: 'UIデザイナー歴5年。最近はFigmaでデザインシステム構築にハマっています。コーヒーとNetflixが好き。',
    location: '東京都渋谷区',
    looking_for: 'work',
    skills: ['Figma', 'UI/UX', 'Adobe XD', 'Sketch', 'Prototyping'],
    interests: ['デザイン', 'カフェ巡り', '映画鑑賞'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-2',
    email: 'kenji.yamamoto@example.com',
    display_name: '山本 健二',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'フルスタックエンジニア。React/Next.jsが得意。オープンソース活動にも興味あり。週末はバスケしてます。',
    location: '神奈川県横浜市',
    looking_for: 'both',
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'AWS'],
    interests: ['プログラミング', 'バスケ', 'ゲーム'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-3',
    email: 'sakura.ito@example.com',
    display_name: '伊藤 さくら',
    avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    bio: 'マーケティング × データ分析が専門。スタートアップでグロースハックしてます。旅行が趣味で年3回は海外へ。',
    location: '東京都目黒区',
    looking_for: 'work',
    skills: ['マーケティング', 'データ分析', 'Python', 'SQL', 'Google Analytics'],
    interests: ['旅行', 'ヨガ', '読書'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-4',
    email: 'takeshi.sato@example.com',
    display_name: '佐藤 武',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    bio: 'プロダクトマネージャー。元エンジニアでスクラム導入が得意。チームビルディングとファシリテーションが好き。',
    location: '東京都港区',
    looking_for: 'volunteer',
    skills: ['プロダクトマネジメント', 'Scrum', 'JIRA', 'ユーザーインタビュー'],
    interests: ['アジャイル', 'キャンプ', '料理'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-5',
    email: 'mika.suzuki@example.com',
    display_name: '鈴木 美香',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
    bio: 'iOSエンジニア3年目。SwiftUIにどっぷり。個人アプリを5本リリース済み。猫を2匹飼ってます。',
    location: '大阪府大阪市',
    looking_for: 'work',
    skills: ['Swift', 'SwiftUI', 'iOS', 'Firebase', 'Core Data'],
    interests: ['アプリ開発', '猫', 'カメラ'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-6',
    email: 'ryo.watanabe@example.com',
    display_name: '渡辺 亮',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    bio: 'バックエンドエンジニア。Go言語とマイクロサービスアーキテクチャが専門。技術ブログ毎週更新中。',
    location: '福岡県福岡市',
    looking_for: 'both',
    skills: ['Go', 'Kubernetes', 'Docker', 'gRPC', 'MySQL'],
    interests: ['技術ブログ', 'ランニング', 'サウナ'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-7',
    email: 'emi.nakamura@example.com',
    display_name: '中村 恵美',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    bio: 'フリーランスのイラストレーター兼デザイナー。企業ロゴからキャラクターデザインまで幅広く対応。',
    location: '京都府京都市',
    looking_for: 'work',
    skills: ['イラスト', 'Photoshop', 'Illustrator', 'Procreate', 'ブランディング'],
    interests: ['アート', '神社巡り', '抹茶'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-8',
    email: 'daiki.kato@example.com',
    display_name: '加藤 大輝',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    bio: 'データサイエンティスト。機械学習モデルの開発と運用が得意。Kaggleコンペにも参加してます。',
    location: '東京都新宿区',
    looking_for: 'volunteer',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'scikit-learn', 'BigQuery'],
    interests: ['機械学習', 'Kaggle', '将棋'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-9',
    email: 'ayaka.yoshida@example.com',
    display_name: '吉田 彩香',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop',
    bio: 'コンテンツマーケター。SEO記事からSNS運用まで。副業でWebライターもやってます。',
    location: '愛知県名古屋市',
    looking_for: 'both',
    skills: ['SEO', 'コンテンツ制作', 'SNSマーケ', 'WordPress', 'ライティング'],
    interests: ['ブログ', 'カフェ', '韓国ドラマ'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-10',
    email: 'shota.tanaka@example.com',
    display_name: '田中 翔太',
    avatar_url: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop',
    bio: 'フロントエンドエンジニア。Vue.js/Nuxt.jsが得意。アクセシビリティとパフォーマンス最適化に興味あり。',
    location: '北海道札幌市',
    looking_for: 'work',
    skills: ['Vue.js', 'Nuxt.js', 'TypeScript', 'Tailwind CSS', 'Vite'],
    interests: ['OSS貢献', 'スノーボード', 'クラフトビール'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
